### ISSUE TITLE
Domain mit Production-Environment verknüpfen

### ISSUE THREAD

**Issue by VitaliaSvirskaja** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#102]
Zu klären
- [x] was machen wir mit der alten Domain (`rgc-nuernberg.de`)?
- [x] können wir nach der Umstellung auf die neue Webseite einen Redirect von `rgc-nuernberg.de` auf `rot-gold-casino.de` einrichten, damit alte Bookmarks nicht kaputt gehen?

TODOs
- [x] Domain `rot-gold-casino.de` für Production-Environment in Vercel konfigurieren
- [x] Redirect von `rot-gold-casino.de` auf `rgc-nuernberg.de` in Strato deaktieren
- [x] Domain `rgc-nuernberg.de` von PortUNA nach Strato übertragen
- [x] Redirect von `rgc-nuernberg.de` auf `rot-gold-casino.de` in Strato konfigurieren

**Comment by DanielMerkl** [comment]
zunächst `production.rot-gold-casino.de`
nach Umstellung auf neue Webseite: `rot-gold-casino.de`
