### ISSUE TITLE
statische Seitengenerierung verbietet Bild optimierung

### ISSUE THREAD

**Issue by schlak** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#31]
Bei der Generierung der statischen Repräsentation der Seite wird nextJS den Fehler, das keine optimierten Bildinhalte verwendet werden dürfen. Wird die Optimierung jedoch deaktiviert werden im fertigen Bild trotzdem versucht die "kleineren" bilder zu laden, was nicht funktioniert. 

![Image](https://user-images.githubusercontent.com/26164340/227718792-b417eec1-1b85-4020-976f-4ec47764b288.png)

**Comment by DanielMerkl** [comment]
Ich schließe mal das Ticket, da das Thema durch #51 abgedeckt werden würde.
