### ISSUE TITLE
Zentralen Account für Development-Environment einrichten

### ISSUE THREAD

**Issue by DanielMerkl** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#43]
TODOs
- [x] E-Mail Account erstellen (z.B. webmaster@rot-gold-casino.de)
- [ ] ~~Daten für Kreditkarte ermitteln (wird für Railway benötigt)~~
- [ ] ~~Railway (CMS & DB)~~
- [x] Vercel (Frontend)
- [x] GitHub
- [x] Cloudinary (Image-Hosting)

**Comment by VitaliaSvirskaja** [comment]
webmaster@rot-gold-casino.de
