### ISSUE TITLE
Nutzung von Google Fonts klären

### ISSUE THREAD

**Issue by DanielMerkl** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#50]
Eventuell können bei Missachtung der gegebenen Ausweisungspflicht Abmahnungen drohen, weshalb die Nutzung der Google Fonts zu klären ist.

**Comment by VitaliaSvirskaja** [comment]
Unsere Art der Verwendung von Google Fonts ist deshalb problemlos, da wir die Fonts als statische Ressource verwenden und diese beim Bauen der statischen Seiten integriert werden und somit keine Google Server angepingt werden.
