### ISSUE TITLE
NextJS Static Exports konfigurieren

### ISSUE THREAD

**Issue by DanielMerkl** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#51]
Für die aktuelle Entwicklungsphase wird das Frontend aktuell auf Vercel gehostet. Langfristig gesehen wird das Ziel sein, nur noch statische Files der fertigen Webseite auf einer DSGVO-konformen Hosting-Plattform abzulegen.

Hierfür muss das NextJS Frontend wie in der folgenden Anleitung konfiguriert werden:
https://nextjs.org/docs/app/building-your-application/deploying/static-exports

Um bei der Webseiten-Performanz keine Rückschritte zu machen, wird für die NextJS Image-Optimization eine benutzerdefinierte Image-Loader Funktion benötigt.
https://nextjs.org/docs/app/building-your-application/deploying/static-exports#image-optimization

**Comment by VitaliaSvirskaja** [comment]
Static Exports mit dem App Router funktionieren aktuell nicht zuverlässig.
Aus diesem Grund soll in der Zwischenzeit ausprobiert werden, ob NextJS in einem Docker mit NodeJS zum laufen gebracht werden kann.
(siehe #87)
