### ISSUE TITLE
Anreden (DU / SIE)

### ISSUE THREAD

**Issue by VitaliaSvirskaja** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#52]

**Comment by DanielMerkl** [comment]
# Meeting 15.07.
Sollte mit Jelena und eventuell auch dem Vereinsvorstand geklärt werden.

**Comment by DanielMerkl** [comment]
in Klärung

**Comment by DanielMerkl** [comment]
Entschluss in Vorstand-Sitzung: Texte sollen einheitlich in Du-Form sein.
