### ISSUE TITLE
Sponsoren überarbeiten

### ISSUE THREAD

**Issue by VitaliaSvirskaja** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-website#97]
TODOs
- [x] klären, ob Auflistung noch aktuell ist
- [x] nicht-aktuelle Sponsoren entfernen
- [x] Icon von Hermann besorgen
- [x] Hermann hinzufügen
- [x] klären, ob Malerbetrieb auch aufgelistet werden soll

**Comment by jmcelic** [comment]
ARAG kann weg als sponsor von der webseite
